env_files:
  github_token: ~/.tokens/github

before:
  hooks:
    - go mod download
    - make -C ./cmd README.md


builds:
- id: linux
  main: ./cmd/main.go
  binary: ez-cgi
  ldflags:
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.version={{.Version}}
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.year=2020
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
    - 386

- id: macos
  main: ./cmd/main.go
  binary: ez-cgi
  ldflags:
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.version={{.Version}}
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.year=2020
  goos:
    - darwin
  goarch:
    - amd64

- id: windows
  main: ./cmd/main.go
  binary: ez-cgi
  ldflags:
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.version={{.Version}}
    - -X github.com/raphaelreyna/ez-cgi/cmd/cmd.year=2020
  goos:
    - windows
  goarch:
    - amd64
    - 386


archives:
- id: brew
  name_template: "ez-cgi_{{ .Version }}.{{ .Os }}_{{ .Arch }}"
  builds:
    - macos
    - linux
  replacements:
    darwin: macos
    amd64: x86_64
    format: zip
  files:
    - LICENSE
    - ./cmd/README.md

- id: windows-zip
  name_template: "ez-cgi_{{ .Version }}.{{ .Os }}_{{ .Arch }}"
  builds:
    - windows
  replacements:
    386: i386
    amd64: x86_64
  format: zip
  files:
    - LICENSE
    - ./cmd/README.md
      
- id: binary
  name_template: "ez-cgi_{{ .Version }}.{{ .Os }}_{{ .Arch }}"
  builds:
    - linux
    - macos
    - windows
  replacements:
    darwin: macos
    386: i386
    amd64: x86_64
  format: binary

checksum:
  name_template: 'checksums.txt'
  
snapshot:
  name_template: "{{ .Tag }}"

brews:
  - name: ez-cgi
    ids:
      - brew
    github:
      owner: raphaelreyna
      name: homebrew-repo
    homepage: "https://github.com/raphaelreyna/ez-cgi/tree/master/cmd"
    description: "A flexible and easy to use CGI HTTP server."

release:
  ids:
    - brew
    - windows-zip
  github:
    owner: raphaelreyna
    name: ez-cgi
  

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
